### ISSUE TITLE
256-bit support

### ISSUE THREAD

**Issue by mvforell** [pheki/xts-mode#1]
Hi there,

first of all thank you for this crate!

It would be great if you could add 256-bit support. I looked into the code and if I understand it correctly (there's a high chance I didn't, I'm still learning cryptography concepts) it's mostly a matter of replacing 128 with 256 / 16 with 32 - though I have no idea what `galois_field_128_mul_le()` does.

Maybe it's possible to avoid code duplication using [const generics](https://github.com/rust-lang/rust/pull/79135) once they're stablilized in Rust 1.50? Until then maybe a macro could do the job.

**Comment by pheki** [comment]
Hi!

Sorry for the late response, but yes, adding 256-bit support isn't supposed to be really hard.

> Maybe it's possible to avoid code duplication using const generics once they're stablilized in Rust 1.50? Until then maybe a macro could do the job.

Yes! This is has been usually done through [typenum](https://crates.io/crates/typenum) in other crypto crates, but I've been avoiding it as it produces very hard to decipher errors and most

**Comment by pheki** [comment]
Hi!

Sorry for the late response, but yes, adding 256-bit support isn't supposed to be really hard.

> Maybe it's possible to avoid code duplication using const generics once they're stablilized in Rust 1.50? Until then maybe a macro could do the job.

Yes! This is has been usually done through [typenum](https://crates.io/crates/typenum) in other crypto crates, but I've been avoiding it as it produces very hard to decipher errors and xts is usually used in 128-bit mode, so I was actually waiting for const generics to stabilize.

On the other hand, using a macro is a very nice idea (specially if it doesn't increase compile times by a lot) for the time being

> though I have no idea what galois_field_128_mul_le() does

Fortunately, I don't think that needs to be touched! Its the Galloi Field multiplication used to recalculate the tweak ([wikipedia](https://en.wikipedia.org/wiki/Disk_encryption_theory#Xor%E2%80%93encrypt%E2%80%93xor_(XEX))), but with AES-256, only the key size is changed to 256-bits, the block size is still 128. (note that I'm also not a cryptographer)

If you're interested in giving it a try, feel free! If not I may do it when I find enough time.

**Comment by mvforell** [comment]
In theory I'd be interested to try out Rust macros and see if I can get it to work. In practice I'll have to see whether I can find time to work on it...

**Comment by mvforell** [comment]
> Fortunately, I don't think that needs to be touched! Its the Galloi Field multiplication used to recalculate the tweak ([wikipedia](https://en.wikipedia.org/wiki/Disk_encryption_theory#Xor%E2%80%93encrypt%E2%80%93xor_(XEX))), but with AES-256, only the key size is changed to 256-bits, the block size is still 128. (note that I'm also not a cryptographer)

I just realized this means that you can already use AES-256 with the existing implementation - that's all I want, no need for 256-bit blocks. Sorry for bothering you!

**Comment by pheki** [comment]
That's true! I actually forgot it was completely generic over the key size :sweat_smile: 

I made it clearer on the README / root docs that 256-bit block support isn't needed for AES-256.

Also no worries, feel free to ask!
